services:
  # Backend API Service
  - type: web
    name: garde-backend
    region: frankfurt
    runtime: docker
    dockerfilePath: ./Dockerfile.render
    dockerContext: ./
    envVars:
      - key: DOCKER_PROFILE
        value: with-redis
      - key: REDIS_HOST
        value: red-d4tv7o1r0fns739fqot0
      - key: REDIS_PORT
        value: "6379"
      - key: REDIS_PASSWORD
        value: "" 
      - key: REDIS_DB
        value: "0"
      - key: PORT
        value: "8443"
      - key: USE_TLS
        value: "false"
      - key: SUPERUSER_EMAIL
        value: test.superuser@test.com
      - key: SUPERUSER_PASSWORD
        value: DevAdminTest123!
      - key: ADMIN_USERS_JSON
        value: '{"test.admin@test.com":"DevAdminTest123!","test.admin.2@test.com":"DevAdminTest123!"}'
      - key: DOMAIN_NAME
        value: ""
    plan: free
    branch: master
